### ISSUE TITLE
hi，about token file problem

### ISSUE THREAD

**Issue by yangkunhub** [damo-cv/TransFGU#1]
ERROR:root:No token file found. Also make sure that a [prod] section with a 'token = value' assignment exists.
I have a question for you，The error is to obtain  token   by    CUDA_VISIBLE_DEVICES=0 python pascalvoc_crop.py，The generated token file is in the trained directory

**Comment by yangkunhub** [comment]
run  CUDA_VISIBLE_DEVICES=0 python pascalvoc_generate_pseudo_label.py with dataset.train_batch_size=8   Tips are as follows：
<img width="526" alt="e403a19ec5cf605d2cc3f60f5ebcdc9" src="https://user-images.githubusercontent.com/95626713/165876066-df85f933-fe7f-49d5-91d0-ff07a518fe43.png">

**Comment by yangkunhub** [comment]
the execution result  about CUDA_VISIBLE_DEVICES=0 python lip_crop.py 。 The PASCAL dataset I used, why is the train/cls_feat/cls_feat_pascalvoc folder empty 。  <img width="376" alt="image" src="https://user-images.githubusercontent.com/95626713/165878906-85194839-3c30-4fc0-be0a-e7725d610c71.png">

**Comment by yangkunhub** [comment]
你好我看了你的论文  你的代码我也去尝试复现了  但是我不知道为什么执行 CUDA_VISIBLE_DEVICES=0 python pascalvoc_crop.py这个命令应该是利用滑动窗口生产裁剪后的图片，但是这些生成后的图片是存放在哪个目录下呢？然后生成train/cls_feat/cls_feat_pascalvoc这个文件下也是为空这个里面应该放的应该是token 文件把 。再执行CUDA_VISIBLE_DEVICES=0 python  pascalvoc _generate_pseudo_label.py with dataset.train_batch_size=2 model.decoder.n_things=16  生成伪标签然后就报错了 。报错如下
<img width="690" alt="image" src="https://user-images.githubusercontent.com/95626713/165880125-facf55d1-29e9-4d2c-91d9-c803063a8a03.png">
这个错误应该是找不到cls-feat文件 。谢谢作者

**Comment by yangkunhub** [comment]
希望能得到作者指点

**Comment by yangkunhub** [comment]
球球了  这篇论文对我很有帮助，  我想问运行了pascalvoc_crop.py，提示是成功运行了如图 
<img width="842" alt="1651288596(1)" src="https://user-images.githubusercontent.com/95626713/166088506-13c4420b-3daf-40e5-a43b-9d05fd0d8273.png">
   但是cls-feat-Pascalvoc 文件夹里的文件是空的，如果这个文件为空下一步在运行pascalvoc _generate_pseudo_label.py 就会提示找不到cls-feat-Pascalvoc文件夹里的文件       就会运行失败  如图
![image](https://user-images.githubusercontent.com/95626713/166088547-4bc0adab-6ffd-4c62-a5c1-6d5448c3362b.png)
 。   我用的是Pascalvoc数据集因为其它数据集太大了我就没试，因为我只用的voc数据集所以root/weight/trained里只放了pascalvoc_decoder.pt。root/weight/dino里都正常放的dino_deitsmall8_pretrain.pth这个文件

**Comment by zyy-cn** [comment]
@yangkunhub hi，您好，抱歉回复迟了。感谢对我们工作的关注。我这边没有复现出这个问题，请问您运行的环境是什么？目录是否具有写权限？

为了排查问题，建议测试如下代码是否能在'train/cls_feat/cls_feat_pascalvoc'文件夹下正常输出'output':

```
import os
import pickle
import numpy as np

feature_bank_dir = os.path.join(f'train/cls_feat/cls_feat_pascalvoc')
os.makedirs(feature_bank_dir, exist_ok=True)
feat_save_path = os.path.join(feature_bank_dir, 'output')
cls_feat = np.random.random((5, 384))
dictfile = open(feat_save_path, 'wb')
pickle.dump(cls_feat, dictfile)
dictfile.close()
```

**Comment by yangkunhub** [comment]
好啦  作者太谢谢你回复我了  问题解决了  因为我在3090上跑的   torch版本有点低了   卸载又换了torch版本 就出现了生成的文件啦

**Comment by yangkunhub** [comment]
你好作者我想在你模型上进行改进，我想在你的decoder（student-teacher）后面加入deeplab里的aspp模块 不知道是否可行

**Comment by yangkunhub** [comment]
你好作者  我遇到了两个问题
一个文件就是我在训练第一轮结束程序就意外报了个错误这个错误如下
![image](https://user-images.githubusercontent.com/95626713/176388552-684edb8a-82ae-49c8-b792-4c7df512dcd4.png)
第二个问题就是我对你的代码进行了修改然后第一轮训练损失函数全变成了0然后也是第一轮训练结束就终止了
![image](https://user-images.githubusercontent.com/95626713/176388994-8ddf0d9f-2a7f-401c-81d1-fe0c62daceb5.png)

**Comment by yangkunhub** [comment]
你好我用你的代码浮现你的论文  我只训练了VOC2012数据集发现我的结果低于你的实验训练结果是参数调整的有问题嘛  训练结果如下ACC  我用的是vit-small8*8训练了100轮但是batchsize我设成了从原来512改成32。然后训练完的模型是在哪个目录里
![image](https://user-images.githubusercontent.com/95626713/176576674-5f420cf1-af24-4cb4-9580-8b08e93acf81.png)

然后我在你代码基础上进行了改动改动完发现训练时的损失函数都为0了这是因为改过的模型没有预训练嘛

**Comment by tanveer6715** [comment]
> ERROR:root:No token file found. Also make sure that a [prod] section with a 'token = value' assignment exists. I have a question for you，The error is to obtain token by CUDA_VISIBLE_DEVICES=0 python pascalvoc_crop.py，The generated token file is in the trained directory

Hi I am facing same problem.. My token files and pseudo_label are generated but when I start training on cityscapes dataset it showed me this error. Your help and suggestion will be appreciated.

**Comment by zyy-cn** [comment]
> > ERROR:root:No token file found. Also make sure that a [prod] section with a 'token = value' assignment exists. I have a question for you，The error is to obtain token by CUDA_VISIBLE_DEVICES=0 python pascalvoc_crop.py，The generated token file is in the trained directory
> 
> Hi I am facing same problem.. My token files and pseudo_label are generated but when I start training on cityscapes dataset it showed me this error. Your help and suggestion will be appreciated.

Hi @tanveer6715 , I didn't reproduce this problem on my end using the environment described in the README.md file. Could you please provide more detail information about this problem if you trained under the same environment?

**Comment by tanveer6715** [comment]
> > > ERROR:root:No token file found. Also make sure that a [prod] section with a 'token = value' assignment exists. I have a question for you，The error is to obtain token by CUDA_VISIBLE_DEVICES=0 python pascalvoc_crop.py，The generated token file is in the trained directory
> > 
> > 
> > Hi I am facing same problem.. My token files and pseudo_label are generated but when I start training on cityscapes dataset it showed me this error. Your help and suggestion will be appreciated.
> 
> Hi @tanveer6715 , I didn't reproduce this problem on my end using the environment described in the README.md file. Could you please provide more detail information about this problem if you trained under the same environment?

Thanks for your kind response. Actually I am trying it on cityscapes dataset and the training starts well. It seems to be a kind of warning message when I start the training.
