### ISSUE TITLE
Training on custom data

### ISSUE THREAD

**Issue by tanveer6715** [damo-cv/TransFGU#2]
Hi,

Great work. I am interested to use this method on my custom dataset. Is it possible to train the model on custom dataset?

**Comment by zyy-cn** [comment]
Hi @tanveer6715 , thank your for your interest in our work. If you only wanna segment the foreground (things) in your custom dataset, you can use our method by taking the following steps:

1. convert your own dataset into PascalVOC-like structure like this:
>     └── YourDataset/
>             ├── JPEGImages/
>             ├── SegmentationClass/
>             └── ImageSets/
>                   └── Segmentation/
>                          ├── train.txt
>                          └── val.txt

2. modify the **line 15** in `configs/pascalvoc.yaml` to your dataset path.
3. modify the **line 37** in `configs/pascalvoc.yaml` to the desired number of classes.
4. run the following training programs to crop images/generate pseudo labels/training the model under your dataset:

> CUDA_VISIBLE_DEVICES=0 python pascalvoc_crop.py
> CUDA_VISIBLE_DEVICES=0 python pascalvoc_generate_pseudo_label.py with dataset.train_batch_size=8
> CUDA_VISIBLE_DEVICES=0,1,2,3 python pascalvoc_trainval.py -F train/pascalvoc with dataset.num_workers=32


If both foreground/background need to be segmented, you can try to adapt our **cityscapes** programs to your dataset in a similar way.

**Comment by tanveer6715** [comment]
> Hi @tanveer6715 , thank your for your interest in our work. If you only wanna segment the foreground (things) in your custom dataset, you can use our method by taking the following steps:
> 
> 1. convert your own dataset into PascalVOC-like structure like this:
> 
> > ```
> > └── YourDataset/
> >         ├── JPEGImages/
> >         ├── SegmentationClass/
> >         └── ImageSets/
> >               └── Segmentation/
> >                      ├── train.txt
> >                      └── val.txt
> > ```
> 
> 2. modify the **line 15** in `configs/pascalvoc.yaml` to your dataset path.
> 3. modify the **line 37** in `configs/pascalvoc.yaml` to the desired number of classes.
> 4. run the following training programs to crop images/generate pseudo labels/training the model under your dataset:
> 
> > CUDA_VISIBLE_DEVICES=0 python pascalvoc_crop.py
> > CUDA_VISIBLE_DEVICES=0 python pascalvoc_generate_pseudo_label.py with dataset.train_batch_size=8
> > CUDA_VISIBLE_DEVICES=0,1,2,3 python pascalvoc_trainval.py -F train/pascalvoc with dataset.num_workers=32
> 
> If both foreground/background need to be segmented, you can try to adapt our **cityscapes** programs to your dataset in a similar way.

Thank you for your reply. Actually I categorized background as 1 class and I have 4 more classes in the dataset, so the total classes are 5 including background. My dataset structure is same like cityscapes so I have to make changes in cityscapes scripts I guess.

**Comment by zyy-cn** [comment]
> > Hi @tanveer6715 , thank your for your interest in our work. If you only wanna segment the foreground (things) in your custom dataset, you can use our method by taking the following steps:
> > 
> > 1. convert your own dataset into PascalVOC-like structure like this:
> > 
> > > ```
> > > └── YourDataset/
> > >         ├── JPEGImages/
> > >         ├── SegmentationClass/
> > >         └── ImageSets/
> > >               └── Segmentation/
> > >                      ├── train.txt
> > >                      └── val.txt
> > > ```
> > 
> > 
> > 
> > 2. modify the **line 15** in `configs/pascalvoc.yaml` to your dataset path.
> > 3. modify the **line 37** in `configs/pascalvoc.yaml` to the desired number of classes.
> > 4. run the following training programs to crop images/generate pseudo labels/training the model under your dataset:
> > 
> > > CUDA_VISIBLE_DEVICES=0 python pascalvoc_crop.py
> > > CUDA_VISIBLE_DEVICES=0 python pascalvoc_generate_pseudo_label.py with dataset.train_batch_size=8
> > > CUDA_VISIBLE_DEVICES=0,1,2,3 python pascalvoc_trainval.py -F train/pascalvoc with dataset.num_workers=32
> > 
> > 
> > If both foreground/background need to be segmented, you can try to adapt our **cityscapes** programs to your dataset in a similar way.
> 
> Thank you for your reply. Actually I categorized background as 1 class and I have 4 more classes in the dataset, so the total classes are 5 including background. My dataset structure is same like cityscapes so I have to make changes in cityscapes scripts I guess.

In official Cityscapes setting, there is no background/foreground definition, so we treat all the area equally rather than make a background/foreground seperation when perform image crop. Actually, there are four strategies we used when we crop images in different dataset, i.e. foreground only (PascalVOC and COCO-80), foreground/background (things/stuff) separation (COCO-Stuff), foreground/background mixed (Cityscapes) and human body centric (LIP), you need to first consider which case your own dataset is fallen into, and then adapt the corresponding scripts.

**Comment by tanveer6715** [comment]
> > > Hi @tanveer6715 , thank your for your interest in our work. If you only wanna segment the foreground (things) in your custom dataset, you can use our method by taking the following steps:
> > > 
> > > 1. convert your own dataset into PascalVOC-like structure like this:
> > > 
> > > > ```
> > > > └── YourDataset/
> > > >         ├── JPEGImages/
> > > >         ├── SegmentationClass/
> > > >         └── ImageSets/
> > > >               └── Segmentation/
> > > >                      ├── train.txt
> > > >                      └── val.txt
> > > > ```
> > > 
> > > 
> > > 
> > > 2. modify the **line 15** in `configs/pascalvoc.yaml` to your dataset path.
> > > 3. modify the **line 37** in `configs/pascalvoc.yaml` to the desired number of classes.
> > > 4. run the following training programs to crop images/generate pseudo labels/training the model under your dataset:
> > > 
> > > > CUDA_VISIBLE_DEVICES=0 python pascalvoc_crop.py
> > > > CUDA_VISIBLE_DEVICES=0 python pascalvoc_generate_pseudo_label.py with dataset.train_batch_size=8
> > > > CUDA_VISIBLE_DEVICES=0,1,2,3 python pascalvoc_trainval.py -F train/pascalvoc with dataset.num_workers=32
> > > 
> > > 
> > > If both foreground/background need to be segmented, you can try to adapt our **cityscapes** programs to your dataset in a similar way.
> > 
> > 
> > Thank you for your reply. Actually I categorized background as 1 class and I have 4 more classes in the dataset, so the total classes are 5 including background. My dataset structure is same like cityscapes so I have to make changes in cityscapes scripts I guess.
> 
> In official Cityscapes setting, there is no background/foreground definition, so we treat all the area equally rather than make a background/foreground seperation when perform image crop. Actually, there four strategies we used when we crop images in different dataset, i.e. foreground only (PascalVOC and COCO-80), foreground/background (things/stuff) separation (COCO-Stuff), foreground/background mixed (Cityscapes) and human body centric (LIP), you need to first consider which case your own dataset is fallen into, and then adapt the corresponding scripts.

Thanks for your detailed reply. First I will try it as Cityscapes. If I have any questions further, I will let you know.

**Comment by tanveer6715** [comment]
Hi, 

Sorry to bother you again. I am working on data having 2 classes. The labels are binary or grey scale images and the original images are RBG. I successfully cropped and generate pseudo labels but when I start training it throw an error (as attached). Kindly let me know any possible solution for it.

![Capture22](https://user-images.githubusercontent.com/84553134/187347456-0cc88cc2-2a66-4f37-a075-99dc380646a2.PNG)

**Comment by zyy-cn** [comment]
> Hi,
> 
> Sorry to bother you again. I am working on data having 2 classes. The labels are binary or grey scale images and the original images are RBG. I successfully cropped and generate pseudo labels but when I start training it throw an error (as attached). Kindly let me know any possible solution for it.
> 
> ![Capture22](https://user-images.githubusercontent.com/84553134/187347456-0cc88cc2-2a66-4f37-a075-99dc380646a2.PNG)

Oh i'm terrible sorry, it seems really a BUG during refactoring. In `line 45 of BootstrappingLoss.py` it should include all the categories in the output mask when calculating the uncertainty loss. I have fixed it and you can try it again with new code.

**Comment by tanveer6715** [comment]
> > Hi,
> > Sorry to bother you again. I am working on data having 2 classes. The labels are binary or grey scale images and the original images are RBG. I successfully cropped and generate pseudo labels but when I start training it throw an error (as attached). Kindly let me know any possible solution for it.
> > ![Capture22](https://user-images.githubusercontent.com/84553134/187347456-0cc88cc2-2a66-4f37-a075-99dc380646a2.PNG)
> 
> Oh i'm terrible sorry, it seems really a BUG during refactoring. In `line 45 of BootstrappingLoss.py` it should include all the categories in the output mask when calculating the uncertainty loss. I have fixed it and you can try it again with new code.

Thank you. It works well now. Saved my time. One last thing when I start training it only utilize 1 GPU memory. But I have 4 GPU's.

**Comment by zyy-cn** [comment]
> > > Hi,
> > > Sorry to bother you again. I am working on data having 2 classes. The labels are binary or grey scale images and the original images are RBG. I successfully cropped and generate pseudo labels but when I start training it throw an error (as attached). Kindly let me know any possible solution for it.
> > > ![Capture22](https://user-images.githubusercontent.com/84553134/187347456-0cc88cc2-2a66-4f37-a075-99dc380646a2.PNG)
> > 
> > 
> > Oh i'm terrible sorry, it seems really a BUG during refactoring. In `line 45 of BootstrappingLoss.py` it should include all the categories in the output mask when calculating the uncertainty loss. I have fixed it and you can try it again with new code.
> 
> Thank you. It works well now. Saved my time. One last thing when I start training it only utilize 1 GPU memory. But I have 4 GPU's.

It sounds strange, could you please provide the detailed output log for my check?

**Comment by tanveer6715** [comment]
> > > > Hi,
> > > > Sorry to bother you again. I am working on data having 2 classes. The labels are binary or grey scale images and the original images are RBG. I successfully cropped and generate pseudo labels but when I start training it throw an error (as attached). Kindly let me know any possible solution for it.
> > > > ![Capture22](https://user-images.githubusercontent.com/84553134/187347456-0cc88cc2-2a66-4f37-a075-99dc380646a2.PNG)
> > > 
> > > 
> > > Oh i'm terrible sorry, it seems really a BUG during refactoring. In `line 45 of BootstrappingLoss.py` it should include all the categories in the output mask when calculating the uncertainty loss. I have fixed it and you can try it again with new code.
> > 
> > 
> > Thank you. It works well now. Saved my time. One last thing when I start training it only utilize 1 GPU memory. But I have 4 GPU's.
> 
> It sounds strange, could you please provide the detailed output log for my check?


Sorry I close the issue by mistake. yes sure. Please have a look into these output files. I have also attached the screenshot of GPU utilization during training.


[cout.txt](https://github.com/damo-cv/TransFGU/files/9458392/cout.txt)
![Capture](https://user-images.githubusercontent.com/84553134/187591876-0e96cf9a-e832-4947-8a95-b0e6d9793cc9.PNG)
![Capture1](https://user-images.githubusercontent.com/84553134/187591958-24d9c941-4f33-455b-8e03-072a04e78499.PNG)

**Comment by zyy-cn** [comment]
> > > > > Hi,
> > > > > Sorry to bother you again. I am working on data having 2 classes. The labels are binary or grey scale images and the original images are RBG. I successfully cropped and generate pseudo labels but when I start training it throw an error (as attached). Kindly let me know any possible solution for it.
> > > > > ![Capture22](https://user-images.githubusercontent.com/84553134/187347456-0cc88cc2-2a66-4f37-a075-99dc380646a2.PNG)
> > > > 
> > > > 
> > > > Oh i'm terrible sorry, it seems really a BUG during refactoring. In `line 45 of BootstrappingLoss.py` it should include all the categories in the output mask when calculating the uncertainty loss. I have fixed it and you can try it again with new code.
> > > 
> > > 
> > > Thank you. It works well now. Saved my time. One last thing when I start training it only utilize 1 GPU memory. But I have 4 GPU's.
> > 
> > 
> > It sounds strange, could you please provide the detailed output log for my check?
> 
> Sorry I close the issue by mistake. yes sure. Please have a look into these output files. I have also attached the screenshot of GPU utilization during training.
> 
> [cout.txt](https://github.com/damo-cv/TransFGU/files/9458392/cout.txt) ![Capture](https://user-images.githubusercontent.com/84553134/187591876-0e96cf9a-e832-4947-8a95-b0e6d9793cc9.PNG) ![Capture1](https://user-images.githubusercontent.com/84553134/187591958-24d9c941-4f33-455b-8e03-072a04e78499.PNG)

Hey, @tanveer6715 I have tried to reproduce this issue in a variant of GPUs but didn't meet a similar problem. I guess something goes wrong when applying the DDP strategy in your runtime environment. I have updated the code and added the DP/DDP switch. You can consider switching the model distributed strategy from DDP to DP by

> CUDA_VISIBLE_DEVICES=0,1,2,3 python cityscapes_trainval.py -F train/cityscapes with dataset.num_workers=32 **model.use_ddp=0**

Please let me know if it works for you.

**Comment by tanveer6715** [comment]
Hey @zyy-cn ,

Thank you for being so helpful. Finally it works for me. Now all 4 GPU's memory have been utilize during training. :)

**Comment by Nonmy** [comment]
Thanks for the innovation work it might help us in future work. It seems that TransFGU can work with RGB image only (without any lable, I'm not pretty sure)  if we don't compute metrics. Is there code for train/val RGB only custom data?
Another question is, can I identify the category of a pixel as its clustered semantic, because it is so segmented.

**Comment by zyy-cn** [comment]
> Thanks for the innovation work it might help us in future work. It seems that TransFGU can work with RGB image only (without any lable, I'm not pretty sure) if we don't compute metrics. Is there code for train/val RGB only custom data? Another question is, can I identify the category of a pixel as its clustered semantic, because it is so segmented.

The semantic prior we used in our method comes from the fixed ViT encoder of DINO, which is trained on the object-centric RGB images, i.e, ImageNet. I'm not sure if such semantic prior can still work when adopting the DINO encoder to another type of image straightly without re-train it. Since DINO trains ViT encoder based on its class-token rather than patch-token, the semantic information contained in class-token (i.e. class feature) would be stronger than patch-token (i.e. pixel feature) and can be used to generate finer-grained segmentation results by our top-down mapping pipeline, especially in the case with a large number of classes (e.g COCO-Stuff 171).

**Comment by Nonmy** [comment]
> > Thanks for the innovation work it might help us in future work. It seems that TransFGU can work with RGB image only (without any lable, I'm not pretty sure) if we don't compute metrics. Is there code for train/val RGB only custom data? Another question is, can I identify the category of a pixel as its clustered semantic, because it is so segmented.
> 
> The semantic prior we used in our method comes from the fixed ViT encoder of DINO, which is trained on the object-centric RGB images, i.e, ImageNet. I'm not sure if such semantic prior can still work when adopting the DINO encoder to another type of image straightly without re-train it. Since DINO trains ViT encoder based on its class-token rather than patch-token, the semantic information contained in class-token (i.e. class feature) would be stronger than patch-token (i.e. pixel feature) and can be used to generate finer-grained segmentation results by our top-down mapping pipeline, especially in the case with a large number of classes (e.g COCO-Stuff 171).

Thank you for replying.
