### ISSUE TITLE
Downloads of Cityscapes Dataset

### ISSUE THREAD

**Issue by YeeZ93** [damo-cv/TransFGU#3]
Hi, thanks for the interesting work!

Could you please check/update the download links of Cityscapes Dataset at this project page? Many thanks!

Best, 
Jun-Pu Zhang

**Comment by zyy-cn** [comment]
@ZHANG-Jun-Pu Sorry for the mistake. The correct links have been updated (you may need to sign in to the official website of Cityscapes first).

**Comment by YeeZ93** [comment]
Thanks for providing the link!
