### ISSUE TITLE
how could i generate the resutls on cocostuff27 with "curated" samples

### ISSUE THREAD

**Issue by mc-lan** [damo-cv/TransFGU#6]
I successfully reproduced the results on cocostuff27: 
INFO - eval_coco - ACC  - All: 44.5856
INFO - eval_coco - mIOU - All: 16.4780

how could I obtain the resutls on cocostuff27 with "curated" samples?

**Comment by zyy-cn** [comment]
Hi:

I've updated the train/val code for the 'curated' data of cocostuff.

**Comment by mc-lan** [comment]
> Hi:
> 
> I've updated the train/val code for the 'curated' data of cocostuff.

Thank you, interesting work!
