### ISSUE TITLE
The following is the final output of training VOC, that is, when saving, there is a problem. I suppose so eval_pascalvoc(cfg, model, val_loader_pascalvoc, history, device, epoch,) Internal error, do not know why. I train with only one gpu. Can the author help me?

### ISSUE THREAD

**Issue by Wabin2022** [damo-cv/TransFGU#7]
..
INFO - train_pascalvoc - train epoch: [0][ 457/ 457]	Time: 1.62 (1.73)	Loss(cat/unc/emb/all): 1.7187/0.8079/0.9578/2.9189 (1.9438/0.8700/0.9989/3.2037)
INFO - train_pascalvoc - * train epoch: [0]	loss(cat/unc/emb/all): 1.9438/0.8700/0.9989/3.2037
ERROR - pascalvoc - Failed after 0:13:26!
Usage:
  pascalvoc_trainval.py [(with UPDATE...)] [options]
  pascalvoc_trainval.py help [COMMAND]
  pascalvoc_trainval.py (-h | --help)
  pascalvoc_trainval.py COMMAND [(with UPDATE...)] [options]
sacred.utils.MissingConfigError: eval_pascalvoc is missing value(s): ['exp_ckpt_dir']

**Comment by zyy-cn** [comment]
Hi @Wabin2022 

Sorry for the inconvenience, it seems to be a bug during refactoring. I have fixed it and you can try it out with the updated code.
